### ISSUE TITLE
signals tb_error unused ,error_found uninitialized in tb_chacha.v

### ISSUE THREAD

**Issue by RakeshpatilLB** [secworks/chacha#4]
In tb_chacha.v the signal tb_error is not used throughout the code and error_found signal is not assigned any value .  The modified code has been attached ,please review it.
[tb_chacha.txt](https://github.com/user-attachments/files/17754594/tb_chacha.txt)

**Comment by secworks** [comment]
Thanks!
Please create a pull request with the patch and I'look at it.
Please also sign the patch. That way you will get the credit and it can be traced to you.
